# https://learn.microsoft.com/windows/wsl/build-custom-distro

[oobe]
command = /etc/oobe.sh
defaultUid = 1000
defaultName = ArchDev

[shortcut]
enabled = true

[windowsterminal]
enabled = true

# TODO once branding is decided:
#   [shortcut] icon = /usr/lib/wsl/icon.ico
#   [windowsterminal] ProfileTemplate = /usr/lib/wsl/terminal-profile.json
